### ISSUE TITLE
location = "embedded" not working with path="mail.compose"

### ISSUE THREAD

**Issue by DanieleVistalli** [ibmverse/verse-developer#17]
I've tried to create an extension point of type "com.ibm.verse.ext.widget" to be used as an embedded composer in the Verse editor (Verse on SmartCloud Notes).

https://ibmverse.github.io/verse-developer/developers/#add-action-for-mail-compose

In the documentation is reported that by using location="embedded" for a path="mail.compose" will make the Widget visible in the message composition area.

I've tried to build my extension, I see backend and postMessages calls to my page but it never gets displayed.

Can you verify this is working and provide a working example ?

Thanks in advace.

**Comment by DanieleVistalli** [comment]
@verse-dev has anybody verified this bug. Is it fixed in 1.0.5 ?

**Comment by icestone2k** [comment]
@DanieleVistalli , thanks for reporting! We will fix this in the release after VoP 1.0.6.

**Comment by DanieleVistalli** [comment]
Thanks @icestone2k . Glad we're getting fixes. I'm mostly a "cloud" user so I would love to be reassured the fix will also work for cloud (when it's released).

**Comment by icestone2k** [comment]
@DanieleVistalli ， it will also be supported in cloud. Please wait for next cloud deployment of Verse. Thanks!

**Comment by DanieleVistalli** [comment]
Thank you for the update. Looking forward to it.

**Comment by DanieleVistalli** [comment]
As of recent Verse version this is now working.
