### ISSUE TITLE
Unable to add extension to Chrome

### ISSUE THREAD

**Issue by tcsoft** [ibmverse/verse-developer#35]
When I try and add the src folder to Chrome it gives the following error.
`Unrecognized manifest key 'applications'.`

Highlighting this line in the manifest.json
` "applications": { "gecko": {"id": "verse_dev_extension@ibm.com", "strict_min_version": "45.0"} },`

I'm using Chrome Version 74.0.3729.131 (Official Build) (64-bit) on Mac OSX 10.14.5

**Comment by panpan-lin** [comment]
Hey I don't work on this project anymore, but I suggest you try to remove this line when adding it to Chrome. It's for `Gecko` (FireFox).

**Comment by tcsoft** [comment]
Thanks, that has worked.
